#!/usr/bin/env bash
set -euo pipefail
CALLER_PWD=$PWD
source "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")/_common.sh"

cd "${CALLER_PWD}"
exec cargo run --manifest-path "${REPO_ROOT}/Cargo.toml" --release -- "$@"
